name: profile_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  shared_preferences:
  path_provider:
  contacts_service: ^0.6.3
  permission_handler: ^10.4.3
  flutter_screenutil: ^5.8.4
  flutter_contacts:
  url_launcher:
  geolocator:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.png
    - assets/images/contact_profile.png
    - assets/images/cloud.png
    - assets/images/contact_profile.png
    - assets/images/barometer.png
    - assets/images/humidity.png
    - assets/images/thermometer.png
    - assets/images/air.png
